# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WXUncaughtExceptionHandler' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for WXUncaughtExceptionHandler
	pod 'SSZipArchive'

  target 'WXUncaughtExceptionHandlerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WXUncaughtExceptionHandlerUITests' do
    # Pods for testing
  end

end
